name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_shaders: ^0.1.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  path_provider: ^2.1.1
  intl: ^0.18.1
  go_router: ^12.1.3
  logging: ^1.2.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  path: ^1.8.3
  clock: ^1.1.1
  time: ^2.1.3
  flex_color_scheme: ^7.3.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  mocktail: ^1.0.2
  objectbox_generator: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/image.jpeg
    - assets/gray.png
    - assets/cloud.jpeg
  shaders:
    - shaders/rain.frag
    - shaders/sunshine.frag
    - shaders/snow.frag
